[package]
name = "mcdl"
version = "0.3.0"
authors = ["paenis <46578974+paenis@users.noreply.github.com>"]
homepage = "https://github.com/paenis/mcdownload"
edition = "2021"


[dependencies]


[profile.release]
debug = 1

[profile.release-small]
inherits = "release"
lto = "thin"
opt-level = "s"
debug = 0

[profile.release-tiny]
inherits = "release"
lto = true
opt-level = "z"
debug = 0
codegen-units = 1
strip = "symbols"
split-debuginfo = "packed"
