[package]
name = "mcdownload"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.1.11", features = ["wrap_help", "cargo"] }
derive_more = { version = "0.99.17", default-features = false, features = ["constructor", "display"] }
itertools = "0.10.5"
lazy_static = "1.4.0"
openssl = { version = "0.10.37", optional = true }
paste = "1.0.12"
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
serde_with = "2.3.1"
term_size = "0.3.2"
tokio = { version = "1.26.0", features = ["full"] }

[features]
vendored-openssl = ["openssl/vendored"]
rustls = ["reqwest/rustls-tls"]
