[package]
name = "mcdl"
version = "0.2.3"
authors = ["paenis <46578974+paenis@users.noreply.github.com>"]
homepage = "https://github.com/paenis/mcdownload"
edition = "2021"
build = "build.rs"

[dependencies]
async_once = "0.2.6"
bytes = "1.4.0"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.2", features = ["derive"] }
color-eyre = "0.6.2"
derive_more = { version = "0.99.17", default-features = false, features = ["constructor", "display"] }
dialoguer = { version = "0.10.4", default-features = false }
directories = "5.0.1"
indicatif = "0.17.5"
itertools = "0.10.5"
lazy_static = "1.4.0"
openssl = { version = "0.10.54", optional = true }
parking_lot = "0.12.1"
paste = "1.0.12"
prettytable-rs = { version = "0.10.0", default-features = false }
regex = "1.8.4"
reqwest = { version = "0.11.18", features = ["json"] }
rmp-serde = "1.1.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_with = "3.0.0"
shell-escape = "0.1.5"
tokio = { version = "1.28.2", features = ["rt-multi-thread", "macros", "fs", "process"] }
toml = { version = "0.7.4", features = ["preserve_order"] }
tracing = "0.1.37"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"
rand = "0.8.5"
scopeguard = { version = "1.1.0", default-features = false }

[build-dependencies]
vergen = { version = "8.2.1", features = ["git", "gitcl", "cargo"] }

[target.'cfg(windows)'.dependencies]
zip = { version = "0.6.6", default-features = false, features = ["deflate"] }

[target.'cfg(unix)'.dependencies]
flate2 = "1.0.26"
tar = "0.4.38"

[features]
vendored-openssl = ["openssl/vendored"]
rustls = ["reqwest/rustls-tls"]
_cross = ["vendored-openssl", "rustls"]

[profile.dev]
opt-level = 1

[profile.release]
debug = 1

[profile.release-small]
inherits = "release"
lto = "thin"
opt-level = "s"
debug = 0

[profile.release-tiny]
inherits = "release"
lto = true
opt-level = "z"
debug = 0
codegen-units = 1
strip = "symbols"
split-debuginfo = "packed"
