[package]
name     = "mcdl"
version  = "0.3.0"
authors  = ["paenis <github+paenis@cark.moe>"]
homepage = "https://github.com/paenis/mcdownload"
edition  = "2021"
build    = "build.rs"

[dependencies]
anyhow = "1.0.95"
bpaf = "0.9.16"
# clap = { version = "4.5.27", features = ["derive"] }
derive_more = { version = "1.0.0", features = ["constructor", "display", "from"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133" 
serde_with = "3.11.0"
ureq = { version = "2.12.1", features = ["json"] }
# toml = "0.8.19"
winnow = "0.6.20"

# async_once = "0.2.6"
# bytes = "1.7.0"
# chrono = { version = "0.4.31", features = ["serde"] }
# color-eyre = "0.6.2"
# dialoguer = { version = "0.11.0", default-features = false }
# directories = "5.0.1"
# indicatif = "0.17.7"
# itertools = "0.13.0"
# lazy_static = "1.5.0"
# parking_lot = "0.12.1"
# paste = "1.0.14"
# prettytable-rs = { version = "0.10.0", default-features = false }
# reqwest = { version = "0.12.7", default-features = false, features = ["charset", "rustls-tls", "http2", "json"]}
# rmp-serde = "1.1.2"
# shell-escape = "0.1.5"
# tokio = { version = "1.39.0", features = ["rt-multi-thread", "macros", "fs", "process"] }
# toml = { version = "0.8.19", features = ["preserve_order"] }
# tracing = "0.1.40"
# tracing-error = "0.2.0"
# tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[features]
default = []
bright-color = ["bpaf/bright-color"]
dull-color = ["bpaf/dull-color"]


[build-dependencies]
rustc_version = "0.4.1"

[profile.release]
debug = 1

[profile.release-small]
inherits  = "release"
lto       = "thin"
opt-level = "s"
debug     = 0

[profile.release-tiny]
inherits        = "release"
lto             = true
opt-level       = "z"
debug           = 0
codegen-units   = 1
strip           = "symbols"
split-debuginfo = "packed"
