[package]
name         = "mcdl"
version      = "0.3.2"
authors      = ["paenis <github+paenis@cark.moe>"]
homepage     = "https://github.com/paenis/mcdownload"
edition      = "2024"
build        = "build.rs"
rust-version = "1.85.0"

[dependencies]
anyhow = "1.0.95"
bpaf = "0.9.19"
const_format = { version = "0.2.34", features = ["fmt"] }
derive_more = { version = "2.0.1", features = ["constructor", "display", "from"] }
http-cache-reqwest = "0.15.1"
jiff = { version = "0.2.12", features = ["serde"] }
reqwest = { version = "0.12.15", default-features = false, features = ["brotli", "deflate", "gzip", "json", "rustls-tls", "zstd"] }
reqwest-middleware = "0.4.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.138"
serde_with = "3.12.0"
tokio = { version = "1.44.2", features = ["rt", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["parking_lot", "env-filter"] }
winnow = "0.7.4"

# bytes = "1.7.0"
# color-eyre = "0.6.2"
# dialoguer = { version = "0.11.0", default-features = false }
# directories = "5.0.1"
# indicatif = "0.17.7"
# parking_lot = "0.12.1"
# prettytable-rs = { version = "0.10.0", default-features = false }
# shell-escape = "0.1.5"
# toml = { version = "0.8.19", features = ["preserve_order"] }
# tracing-error = "0.2.0"

[features]
default      = []
bright-color = ["bpaf/bright-color"]
dull-color   = ["bpaf/dull-color"]


[build-dependencies]
rustc_version = "0.4.1"

[profile.release]
debug = "limited"
lto   = "thin"

[profile.overkill]
inherits        = "release"
lto             = "fat"
debug           = 0
codegen-units   = 1
strip           = true