[package]
name = "mcdownload"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "4.1.11", features = ["wrap_help", "cargo"] }
itertools = "0.10.5"
lazy_static = "1.4.0"
regex = "1.7.1"
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.157", features = ["derive"] }
serde_json = "1.0.94"
serde_with = "2.3.1"
tokio = { version = "1.26.0", features = ["full"] }
