name: build
run-name: build mcdl@${{ github.ref_name == 'main' && github.sha || github.ref_name }}
on: 
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      runner:
        required: true
        type: string
      command:
        required: true
        type: string
      profile:
        required: false
        type: string
        default: release
      artifacts_retention_days:
        required: false
        type: number
        default: 7

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: rui314/setup-mold@v1

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: "${{ inputs.target }}"

      - name: Setup Cache
        if: inputs.command != 'cross'
        uses: Swatinem/rust-cache@v2

      - name: Install Cross
        if: inputs.command == 'cross'
        shell: bash
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cross --force

      - name: Build artifacts
        run: ${{ inputs.command }} --config .cargo/config-ci.toml build --verbose --profile ${{ inputs.profile }} --target ${{ inputs.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mcdl-${{ github.ref_name == 'main' && github.sha || github.ref_name }}-${{ inputs.target }}
          path: target/${{ inputs.target }}/release/mcdl${{ startsWith(inputs.runner, 'windows') && '.exe' || '' }}
          retention-days: ${{ inputs.artifacts_retention_days }}
