name: build artifacts
run-name: build artifacts for ${{ github.ref_name }}@${{ github.sha }}
on: [workflow_call, workflow_dispatch]

jobs:
  build:
    name: build ${{ matrix.profile }} for ${{ matrix.build }}
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      BUILD_DIR: ${{ matrix.profile != 'dev' && matrix.profile || 'debug' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          [linux, windows-msvc]
        profile:
          [release] 
        include:
          - build: linux
            os: ubuntu-latest
          - build: windows-msvc
            os: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4

      - name: Build
        run: cargo build --verbose --profile ${{ matrix.profile }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build }}.nightly.${{ matrix.profile }}
          path: |
            ./target/${{ env.BUILD_DIR }}/mcdl*
            !./target/${{ env.BUILD_DIR }}/mcdl.d
  
  build-crossplatform:
    needs: [build] # wait for normal builds (faster)
    name: build ${{ matrix.profile }} for ${{ matrix.build }}
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      BUILD_DIR: ${{ matrix.profile != 'dev' && matrix.profile || 'debug' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          [linux-aarch64]
        profile:
          [release]
        include:
          - build: linux-aarch64
            os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Use Cross
        run: |
          cargo install cross
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
          echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

      - name: Build
        run: cross build --verbose --target ${{ matrix.target }} --profile ${{ matrix.profile }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build }}.nightly.${{ matrix.profile }}
          path: |
            ./target/${{ matrix.target }}/${{ env.BUILD_DIR }}/mcdl*
            !./target/${{ matrix.target }}/${{ env.BUILD_DIR }}/mcdl.d
