name: build artifacts
run-name: build artifacts for ${{ github.ref_name }}@${{ github.sha }}
on: [workflow_call]

jobs:
  build:
    name: build ${{ matrix.profile }} for ${{ matrix.build }}
    env:
        CARGO: cargo
        TARGET_FLAGS: ""
        TARGET_DIR: ./target
        OTHER_FLAGS: ${{ matrix.flags }}
        PROFILE: ${{ matrix.profile }}
        BUILD_DIR: ${{ matrix.profile != 'dev' && matrix.profile || 'debug' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
          [linux-nightly, linux-nightly-aarch64, win-msvc]
        profile:
          [release, release-nodebug] 
        include:
          # - build: linux-stable
          #   os: ubuntu-22.04
          #   rust: stable
          # - build: linux-beta
          #   os: ubuntu-22.04
          #   rust: beta
          - build: linux-nightly
            os: ubuntu-22.04
            rust: nightly
          # - build: linux-nightly-musl
          #   os: ubuntu-22.04
          #   rust: nightly
          #   target: x86_64-unknown-linux-musl
          #   flags: --features vendored-openssl --features rustls
          # - build: linux-nightly-armv6
          #   os: ubuntu-22.04
          #   rust: nightly
          #   target: arm-unknown-linux-gnueabihf
          #   flags: --features vendored-openssl --features rustls
          - build: linux-nightly-aarch64
            os: ubuntu-22.04
            rust: nightly
            target: aarch64-unknown-linux-gnu
            flags: --features vendored-openssl --features rustls
          # - build: linux-nightly-aarch64-musl
          #   os: ubuntu-22.04
          #   rust: nightly
          #   target: aarch64-unknown-linux-musl
          #   flags: --features vendored-openssl --features rustls
          - build: win-msvc
            os: windows-2022
            rust: nightly
          # - build: win-gnu
          #   os: windows-2022
          #   rust: nightly-x86_64-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages (Ubuntu)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends --reinstall \
            openssl libssl-dev openssl musl-tools
          export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig/

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Use Cross
        if: matrix.target != ''
        run: |
          cargo install cross
          echo "CARGO=cross" >> $GITHUB_ENV
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
          echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

      - name: Build
        run: ${{ env.CARGO }} build --verbose ${{ env.TARGET_FLAGS }} ${{ env.OTHER_FLAGS }} --profile ${{ env.PROFILE }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.build }}-${{ env.PROFILE }}
          path: |
            ${{ env.TARGET_DIR }}/${{ env.BUILD_DIR }}/mcdownload*
            !${{ env.TARGET_DIR }}/${{ env.BUILD_DIR }}/mcdownload.d
