name: nightly
run-name: build nightly mcdl @ ${{ github.sha }}
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  nightly:
    uses: paenis/mcdownload/.github/workflows/build.yml@main
    with:
      target: ${{ matrix.target }}
      runner: ${{ matrix.runner }}
      command: ${{ matrix.command }}
      artifacts_retention_days: 2

    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          runner: ubuntu-latest
          command: cargo
        - target: x86_64-pc-windows-msvc
          runner: windows-latest
          command: cargo
        - target: aarch64-apple-darwin
          runner: macos-latest
          command: cargo
