name: release
run-name: release mcdl@${{ github.ref_name == 'refs/heads/main' && github.sha || github.ref_name }}
on:
  push:
    branches: [main]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          runner: ubuntu-latest
          command: cargo
        - target: x86_64-pc-windows-msvc
          runner: windows-latest
          command: cargo
        - target: aarch64-apple-darwin
          runner: macos-latest
          command: cargo

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build artifacts
        uses: ./build.yml
        with:
          target: ${{ matrix.target }}
          runner: ${{ matrix.runner }}
          command: ${{ matrix.command }}
          upload_artifacts: false

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/${{ matrix.target }}/release/mcdl
          allowUpdates: true