name: release
run-name: release mcdl@${{ github.ref_name == 'refs/heads/main' && github.sha || github.ref_name }}
on:
  push:
    branches: [main]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    uses: paenis/mcdownload/.github/workflows/build.yml@main
    with:
      target: ${{ matrix.target }}
      runner: ${{ matrix.runner }}
      command: ${{ matrix.command }}
      upload_artifacts: false

    strategy:
      fail-fast: false
      matrix:
        include:
        - target: x86_64-unknown-linux-gnu
          runner: ubuntu-latest
          command: cargo
        - target: x86_64-pc-windows-msvc
          runner: windows-latest
          command: cargo
        - target: aarch64-apple-darwin
          runner: macos-latest
          command: cargo

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: target/*/release/mcdl
          allowUpdates: true