name: test
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"

concurrency:
  group: test

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: rustup show
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo nextest run --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runner }}.stable.debug
          path: |
            ./target/debug/mcdl*
            !./target/debug/mcdl.d
          retention-days: 7
