name: ci
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  test-linux:
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup show

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run Clippy
        run: cargo clippy

      - name: Run tests
        run: cargo nextest run --release

  test-windows:
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: rustup show

      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.4

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run Clippy
        run: cargo clippy

      - name: Run tests
        run: cargo nextest run --release

  trigger-build:
    name: trigger build
    needs: [test-linux, test-windows]
    uses: ./.github/workflows/build.yml

